name: DeployToGhPages

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "Lint" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  deploy-to-gh-pages:
    strategy:
      matrix:
        node-version: [ 14.x ]

    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: npm ci
    - name: Run deploy to gh-pages
      run: npm run deploy
